name = "aiaistream-tts-logger"
main = "src/index.js"
compatibility_date = "2024-12-01"

[env.production]
name = "aiaistream-tts-logger-production"

[[env.production.kv_namespaces]]
binding = "TTS_LOGS"
id = "74f3173468294bc2aa1b8cd4f2b5d942"
